### ISSUE TITLE
ofJson does not name a type.

### ISSUE THREAD

**Issue by trykks** [robotconscience/ofxLibwebsockets#85] opened 2016-04-02 00:53 UTC
Hi there!

I'm awfully new to this ordeal so forgive me if I'm missing something obvious.

When running make in the example_client_hello_world folder I get the following compile error:

-------------------------------------------------------------------------------------------------------------------------
In file included from /home/trykks/of_v0.9.3_linux64_release/addons/ofxLibwebsockets/libs/ofxLibwebsockets/include/ofxLibwebsockets/Protocol.h:14:0,
                 from /home/trykks/of_v0.9.3_linux64_release/addons/ofxLibwebsockets/libs/ofxLibwebsockets/include/ofxLibwebsockets/Reactor.h:13,
                 from /home/trykks/of_v0.9.3_linux64_release/addons/ofxLibwebsockets/libs/ofxLibwebsockets/include/ofxLibwebsockets/Util.h:15,
                 from /home/trykks/of_v0.9.3_linux64_release/addons/ofxLibwebsockets/src/ofxLibwebsockets.h:3,
                 from /home/trykks/of_v0.9.3_linux64_release/addons/ofxLibwebsockets/example_client_hello_world/src/ofApp.h:5,
                 from /home/trykks/of_v0.9.3_linux64_release/addons/ofxLibwebsockets/example_client_hello_world/src/ofApp.cpp:1:
/home/trykks/of_v0.9.3_linux64_release/addons/ofxLibwebsockets/libs/ofxLibwebsockets/include/ofxLibwebsockets/Events.h:22:9: error: ‘ofJson’ does not name a type
         ofJson json;
         ^

-------------------------------------------------------------------------------------------------------------------------

Any clues on what might be funky?

Using latest download of OF from the website and the latest repo from here.

Cheers,
TRyKKs

**Comment by robotconscience** [comment] 2016-04-02 00:56
Hello!

This is my mistake! Thanks for reminding me. If you try downloading/cloning
the last tag (0.9.0, under releases), things will be all good. My
understanding was that 0.9.2+ had ofJson, but that's not the case!
On Fri, Apr 1, 2016 at 8:53 PM trykks <notifications@github.com> wrote:

> Hi there!
>
> I'm awfully new to this ordeal so forgive me if I'm missing something
> obvious.
>
> When running make in the example_client_hello_world folder I get the
> following compile error:
> ------------------------------
>
> In file included from
> /home/trykks/of_v0.9.3_linux64_release/addons/ofxLibwebsockets/libs/ofxLibwebsockets/include/ofxLibwebsockets/Protocol.h:14:0,
> from
> /home/trykks/of_v0.9.3_linux64_release/addons/ofxLibwebsockets/libs/ofxLibwebsockets/include/ofxLibwebsockets/Reactor.h:13,
> from
> /home/trykks/of_v0.9.3_linux64_release/addons/ofxLibwebsockets/libs/ofxLibwebsockets/include/ofxLibwebsockets/Util.h:15,
> from
> /home/trykks/of_v0.9.3_linux64_release/addons/ofxLibwebsockets/src/ofxLibwebsockets.h:3,
> from
> /home/trykks/of_v0.9.3_linux64_release/addons/ofxLibwebsockets/example_client_hello_world/src/ofApp.h:5,
> from
> /home/trykks/of_v0.9.3_linux64_release/addons/ofxLibwebsockets/example_client_hello_world/src/ofApp.cpp:1:
> /home/trykks/of_v0.9.3_linux64_release/addons/ofxLibwebsockets/libs/ofxLibwebsockets/include/ofxLibwebsockets/Events.h:22:9:
> error: ‘ofJson’ does not name a type
> ofJson json;
> ^
> ------------------------------
>
> Any clues on what might be funky?
>
> Using latest download of OF from the website and the latest repo from here.
>
> Cheers,
> TRyKKs
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/robotconscience/ofxLibwebsockets/issues/85>
>
-- 
Brett Renfer
\\ robotconscience.com
// tsps.cc

**Comment by robotconscience** [comment] 2016-04-02 00:56
Will push a fix to master ASAP as well.
On Fri, Apr 1, 2016 at 8:56 PM Brett Renfer <brett@robotconscience.com>
wrote:

> Hello!
>
> This is my mistake! Thanks for reminding me. If you try
> downloading/cloning the last tag (0.9.0, under releases), things will be
> all good. My understanding was that 0.9.2+ had ofJson, but that's not the
> case!
> On Fri, Apr 1, 2016 at 8:53 PM trykks <notifications@github.com> wrote:
>
>> Hi there!
>>
>> I'm awfully new to this ordeal so forgive me if I'm missing something
>> obvious.
>>
>> When running make in the example_client_hello_world folder I get the
>> following compile error:
>> ------------------------------
>>
>> In file included from
>> /home/trykks/of_v0.9.3_linux64_release/addons/ofxLibwebsockets/libs/ofxLibwebsockets/include/ofxLibwebsockets/Protocol.h:14:0,
>> from
>> /home/trykks/of_v0.9.3_linux64_release/addons/ofxLibwebsockets/libs/ofxLibwebsockets/include/ofxLibwebsockets/Reactor.h:13,
>> from
>> /home/trykks/of_v0.9.3_linux64_release/addons/ofxLibwebsockets/libs/ofxLibwebsockets/include/ofxLibwebsockets/Util.h:15,
>> from
>> /home/trykks/of_v0.9.3_linux64_release/addons/ofxLibwebsockets/src/ofxLibwebsockets.h:3,
>> from
>> /home/trykks/of_v0.9.3_linux64_release/addons/ofxLibwebsockets/example_client_hello_world/src/ofApp.h:5,
>> from
>> /home/trykks/of_v0.9.3_linux64_release/addons/ofxLibwebsockets/example_client_hello_world/src/ofApp.cpp:1:
>> /home/trykks/of_v0.9.3_linux64_release/addons/ofxLibwebsockets/libs/ofxLibwebsockets/include/ofxLibwebsockets/Events.h:22:9:
>> error: ‘ofJson’ does not name a type
>> ofJson json;
>> ^
>> ------------------------------
>>
>> Any clues on what might be funky?
>>
>> Using latest download of OF from the website and the latest repo from
>> here.
>>
>> Cheers,
>> TRyKKs
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/robotconscience/ofxLibwebsockets/issues/85>
>>
> --
> Brett Renfer
> \\ robotconscience.com
> // tsps.cc
>
-- 
Brett Renfer
\\ robotconscience.com
// tsps.cc

**Comment by trykks** [comment] 2016-04-02 01:06
Thank you for the incredibly quick reply!

I cloned 0.9.0 and tried to run make again, but the same compile error appears.
I also tried 0.9.2 in case I misunderstood you, same result.

Do I have to recompile OF for each addon?

**Comment by robotconscience** [comment] 2016-04-02 01:09
Oh sorry, my bad! Clone/download the 0.9.0 version of this addon, OF is
totally fine.
https://github.com/robotconscience/ofxLibwebsockets/releases/tag/0.9.0
On Fri, Apr 1, 2016 at 9:06 PM trykks <notifications@github.com> wrote:

> Thank you for the incredibly quick reply!
>
> I cloned 0.9.0 and tried to run make again, but the same compile error
> appears.
> I also tried 0.9.2 in case I misunderstood you, same result.
>
> Do I have to recompile OF for each addon?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/robotconscience/ofxLibwebsockets/issues/85#issuecomment-204621285>
>
-- 
Brett Renfer
\\ robotconscience.com
// tsps.cc

**Comment by trykks** [comment] 2016-04-02 01:19
I just copied the contents of that release into my existing ofxLibwebsockets folder in /addons replacing as it prompted and it now works!

Only running the release caused it to not find ofxLibwebsockets.h, so I assumed this was the right way to do it.

Thank you! Saved me a lot of headaches.

**Comment by robotconscience** [comment] 2016-04-02 01:21
Perfect! Sorry again, should have caught the ofJson thing sooner. Good
luck, don't hesitate to post if you have other issues.
On Fri, Apr 1, 2016 at 9:19 PM trykks <notifications@github.com> wrote:

> I just copied the contents of that release into my existing
> ofxLibwebsockets folder in /addons replacing as it prompted and it now
> works!
>
> Only running the release caused it to not find ofxLibwebsockets.h, so I
> assumed this was the right way to do it.
>
> Thank you! Saved me a lot of headaches.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/robotconscience/ofxLibwebsockets/issues/85#issuecomment-204623276>
>
-- 
Brett Renfer
\\ robotconscience.com
// tsps.cc

**Comment by joernroeder** [comment] 2016-04-03 20:58
@robotconscience same problem here but it wasn't obvious to find the issue as it's closed and therefore doesn't show up in the issue list with default filters. Please reopen the issue so other people like me can find it easier and close it when it's fixed on master – thanks!

If you have the same issue just clone the addon to your addons folder and swich to the suggested `0.9.0` tag to get it up and running again. 
After the issue is fixed you can switch back to master …

```
cd /of_release/addons
git clone https://github.com/robotconscience/ofxLibwebsockets.git
git checkout 0.9.0
// when the issue get's fixed
git checkout master
```

**Comment by robotconscience** [comment] 2016-04-03 21:04
Didn't realize it's closed! Will fix soon, sorry again. The other alt is to use OF from GitHub with the current master.

**Comment by trykks** [comment] 2016-04-03 21:11
And I didn't know what the standard convention regarding issues was, my bad :)

**Comment by robotconscience** [comment] 2016-04-04 00:55
OK! This is fixed now in master. I'd recommend using the master branch, as there are some small fixes/optimizations that will help your projects run better and consume less resources.

**Closed by robotconscience** 2016-04-04 00:55 UTC
